python3 ../weight_analysis.py clean_model/epoch_0.pth clean_model/epoch_1.pth
python3 ../weight_analysis.py clean_model/epoch_1.pth clean_model/epoch_2.pth
python3 ../weight_analysis.py clean_model/epoch_2.pth clean_model/epoch_3.pth
python3 ../weight_analysis.py clean_model/epoch_3.pth clean_model/epoch_4.pth
python3 ../weight_analysis.py clean_model/epoch_4.pth clean_model/epoch_5.pth
python3 ../weight_analysis.py clean_model/epoch_5.pth clean_model/epoch_6.pth
python3 ../weight_analysis.py clean_model/epoch_6.pth clean_model/epoch_7.pth
python3 ../weight_analysis.py clean_model/epoch_7.pth clean_model/epoch_8.pth
python3 ../weight_analysis.py clean_model/epoch_8.pth clean_model/epoch_9.pth
python3 ../weight_analysis.py clean_model/epoch_9.pth clean_model/epoch_10.pth
python3 ../weight_analysis.py clean_model/epoch_10.pth clean_model/epoch_11.pth
python3 ../weight_analysis.py clean_model/epoch_11.pth clean_model/epoch_12.pth
python3 ../weight_analysis.py clean_model/epoch_12.pth clean_model/epoch_13.pth
python3 ../weight_analysis.py clean_model/epoch_13.pth clean_model/epoch_14.pth
python3 ../weight_analysis.py clean_model/epoch_14.pth clean_model/epoch_15.pth
python3 ../weight_analysis.py clean_model/epoch_15.pth clean_model/epoch_16.pth
python3 ../weight_analysis.py clean_model/epoch_16.pth clean_model/epoch_17.pth
python3 ../weight_analysis.py clean_model/epoch_17.pth clean_model/epoch_18.pth
python3 ../weight_analysis.py clean_model/epoch_18.pth clean_model/epoch_19.pth
python3 ../weight_analysis.py clean_model/epoch_19.pth clean_model/epoch_20.pth
python3 ../weight_analysis.py clean_model/epoch_20.pth clean_model/epoch_21.pth
python3 ../weight_analysis.py clean_model/epoch_21.pth clean_model/epoch_22.pth
python3 ../weight_analysis.py clean_model/epoch_22.pth clean_model/epoch_23.pth
python3 ../weight_analysis.py clean_model/epoch_23.pth clean_model/epoch_24.pth
python3 ../weight_analysis.py clean_model/epoch_24.pth clean_model/epoch_25.pth
python3 ../weight_analysis.py clean_model/epoch_25.pth clean_model/epoch_26.pth
python3 ../weight_analysis.py clean_model/epoch_26.pth clean_model/epoch_27.pth
python3 ../weight_analysis.py clean_model/epoch_27.pth clean_model/epoch_28.pth
python3 ../weight_analysis.py clean_model/epoch_28.pth clean_model/epoch_29.pth
python3 ../weight_analysis.py clean_model/epoch_29.pth clean_model/epoch_30.pth
python3 ../weight_analysis.py clean_model/epoch_30.pth clean_model/epoch_31.pth
python3 ../weight_analysis.py clean_model/epoch_31.pth clean_model/epoch_32.pth
python3 ../weight_analysis.py clean_model/epoch_32.pth clean_model/epoch_33.pth
python3 ../weight_analysis.py clean_model/epoch_33.pth clean_model/epoch_34.pth
python3 ../weight_analysis.py clean_model/epoch_34.pth clean_model/epoch_35.pth
python3 ../weight_analysis.py clean_model/epoch_35.pth clean_model/epoch_36.pth
python3 ../weight_analysis.py clean_model/epoch_36.pth clean_model/epoch_37.pth
python3 ../weight_analysis.py clean_model/epoch_37.pth clean_model/epoch_38.pth
python3 ../weight_analysis.py clean_model/epoch_38.pth clean_model/epoch_39.pth
python3 ../weight_analysis.py clean_model/epoch_39.pth clean_model/epoch_40.pth
python3 ../weight_analysis.py clean_model/epoch_40.pth clean_model/epoch_41.pth
python3 ../weight_analysis.py clean_model/epoch_41.pth clean_model/epoch_42.pth
python3 ../weight_analysis.py clean_model/epoch_42.pth clean_model/epoch_43.pth
python3 ../weight_analysis.py clean_model/epoch_43.pth clean_model/epoch_44.pth
python3 ../weight_analysis.py clean_model/epoch_44.pth clean_model/epoch_45.pth
python3 ../weight_analysis.py clean_model/epoch_45.pth clean_model/epoch_46.pth
python3 ../weight_analysis.py clean_model/epoch_46.pth clean_model/epoch_47.pth
python3 ../weight_analysis.py clean_model/epoch_47.pth clean_model/epoch_48.pth
python3 ../weight_analysis.py clean_model/epoch_48.pth clean_model/epoch_49.pth
python3 ../weight_analysis.py clean_model/epoch_49.pth clean_model/epoch_50.pth
python3 ../weight_analysis.py clean_model/epoch_50.pth clean_model/epoch_51.pth
python3 ../weight_analysis.py clean_model/epoch_51.pth clean_model/epoch_52.pth
python3 ../weight_analysis.py clean_model/epoch_52.pth clean_model/epoch_53.pth
python3 ../weight_analysis.py clean_model/epoch_53.pth clean_model/epoch_54.pth
python3 ../weight_analysis.py clean_model/epoch_54.pth clean_model/epoch_55.pth
python3 ../weight_analysis.py clean_model/epoch_55.pth clean_model/epoch_56.pth
python3 ../weight_analysis.py clean_model/epoch_56.pth clean_model/epoch_57.pth
python3 ../weight_analysis.py clean_model/epoch_57.pth clean_model/epoch_58.pth
python3 ../weight_analysis.py clean_model/epoch_58.pth clean_model/epoch_59.pth
python3 ../weight_analysis.py clean_model/epoch_59.pth clean_model/epoch_60.pth
python3 ../weight_analysis.py clean_model/epoch_60.pth clean_model/epoch_61.pth
python3 ../weight_analysis.py clean_model/epoch_61.pth clean_model/epoch_62.pth
python3 ../weight_analysis.py clean_model/epoch_62.pth clean_model/epoch_63.pth
python3 ../weight_analysis.py clean_model/epoch_63.pth clean_model/epoch_64.pth
python3 ../weight_analysis.py clean_model/epoch_64.pth clean_model/epoch_65.pth
python3 ../weight_analysis.py clean_model/epoch_65.pth clean_model/epoch_66.pth
python3 ../weight_analysis.py clean_model/epoch_66.pth clean_model/epoch_67.pth
python3 ../weight_analysis.py clean_model/epoch_67.pth clean_model/epoch_68.pth
python3 ../weight_analysis.py clean_model/epoch_68.pth clean_model/epoch_69.pth
python3 ../weight_analysis.py clean_model/epoch_69.pth clean_model/epoch_70.pth
python3 ../weight_analysis.py clean_model/epoch_70.pth clean_model/epoch_71.pth
python3 ../weight_analysis.py clean_model/epoch_71.pth clean_model/epoch_72.pth
python3 ../weight_analysis.py clean_model/epoch_72.pth clean_model/epoch_73.pth
python3 ../weight_analysis.py clean_model/epoch_73.pth clean_model/epoch_74.pth
python3 ../weight_analysis.py clean_model/epoch_74.pth clean_model/epoch_75.pth
python3 ../weight_analysis.py clean_model/epoch_75.pth clean_model/epoch_76.pth
python3 ../weight_analysis.py clean_model/epoch_76.pth clean_model/epoch_77.pth
python3 ../weight_analysis.py clean_model/epoch_77.pth clean_model/epoch_78.pth
python3 ../weight_analysis.py clean_model/epoch_78.pth clean_model/epoch_79.pth
python3 ../weight_analysis.py clean_model/epoch_79.pth clean_model/epoch_80.pth
python3 ../weight_analysis.py clean_model/epoch_80.pth clean_model/epoch_81.pth
python3 ../weight_analysis.py clean_model/epoch_81.pth clean_model/epoch_82.pth
python3 ../weight_analysis.py clean_model/epoch_82.pth clean_model/epoch_83.pth
python3 ../weight_analysis.py clean_model/epoch_83.pth clean_model/epoch_84.pth
python3 ../weight_analysis.py clean_model/epoch_84.pth clean_model/epoch_85.pth
python3 ../weight_analysis.py clean_model/epoch_85.pth clean_model/epoch_86.pth
python3 ../weight_analysis.py clean_model/epoch_86.pth clean_model/epoch_87.pth
python3 ../weight_analysis.py clean_model/epoch_87.pth clean_model/epoch_88.pth
python3 ../weight_analysis.py clean_model/epoch_88.pth clean_model/epoch_89.pth
python3 ../weight_analysis.py clean_model/epoch_89.pth clean_model/epoch_90.pth
python3 ../weight_analysis.py clean_model/epoch_90.pth clean_model/epoch_91.pth
python3 ../weight_analysis.py clean_model/epoch_91.pth clean_model/epoch_92.pth
python3 ../weight_analysis.py clean_model/epoch_92.pth clean_model/epoch_93.pth
python3 ../weight_analysis.py clean_model/epoch_93.pth clean_model/epoch_94.pth
python3 ../weight_analysis.py clean_model/epoch_94.pth clean_model/epoch_95.pth
python3 ../weight_analysis.py clean_model/epoch_95.pth clean_model/epoch_96.pth
python3 ../weight_analysis.py clean_model/epoch_96.pth clean_model/epoch_97.pth
python3 ../weight_analysis.py clean_model/epoch_97.pth clean_model/epoch_98.pth
python3 ../weight_analysis.py clean_model/epoch_98.pth clean_model/epoch_99.pth
python3 ../weight_analysis.py clean_model/epoch_99.pth poisoned_model/epoch_100.pth
python3 ../weight_analysis.py poisoned_model/epoch_100.pth poisoned_model/epoch_101.pth
python3 ../weight_analysis.py poisoned_model/epoch_101.pth poisoned_model/epoch_102.pth
python3 ../weight_analysis.py poisoned_model/epoch_102.pth poisoned_model/epoch_103.pth
python3 ../weight_analysis.py poisoned_model/epoch_103.pth poisoned_model/epoch_104.pth
python3 ../weight_analysis.py poisoned_model/epoch_104.pth poisoned_model/epoch_105.pth
python3 ../weight_analysis.py poisoned_model/epoch_105.pth poisoned_model/epoch_106.pth
python3 ../weight_analysis.py poisoned_model/epoch_106.pth poisoned_model/epoch_107.pth
python3 ../weight_analysis.py poisoned_model/epoch_107.pth poisoned_model/epoch_108.pth
python3 ../weight_analysis.py poisoned_model/epoch_108.pth poisoned_model/epoch_109.pth
