# Clean training
python3 brew_poison.py --poisonkey 0 --modelkey 0 --deterministic --optimization basic --only_clean_training --epochs 10                                                                                   --modelsave_path models/higher_budget/all_clean      --save_epoch 9   --lr 0.01 --targets 1000 --recipe patch                  --save_weights untimed --budget 0.1
python3 brew_poison.py --poisonkey 0 --modelkey 0 --deterministic --optimization basic --only_clean_training --epochs 10 --load_model models/higher_budget/all_clean/clean_model/full_epoch_9.pth          --modelsave_path models/higher_budget/all_clean      --save_epoch 19  --lr 0.01 --targets 1000 --recipe patch --start_from 10  --save_weights untimed --budget 0.1
python3 brew_poison.py --poisonkey 0 --modelkey 0 --deterministic --optimization basic --only_clean_training --epochs 10 --load_model models/higher_budget/all_clean/clean_model/full_epoch_19.pth         --modelsave_path models/higher_budget/all_clean      --save_epoch 29  --lr 0.01 --targets 1000 --recipe patch --start_from 20  --save_weights untimed --budget 0.1
python3 brew_poison.py --poisonkey 0 --modelkey 0 --deterministic --optimization basic --only_clean_training --epochs 10 --load_model models/higher_budget/all_clean/clean_model/full_epoch_29.pth         --modelsave_path models/higher_budget/all_clean      --save_epoch 39  --lr 0.01 --targets 1000 --recipe patch --start_from 30  --save_weights untimed --budget 0.1

# First quarter poisoned
python3 brew_poison.py --poisonkey 0 --modelkey 0 --deterministic --optimization basic --skip_clean_training --epochs 10                                                                                   --modelsave_path models/higher_budget/first_quarter  --save_epoch 9   --lr 0.01 --targets 1000 --recipe patch                  --save_weights untimed --budget 0.1
python3 brew_poison.py --poisonkey 0 --modelkey 0 --deterministic --optimization basic --only_clean_training --epochs 10 --load_model models/higher_budget/first_quarter/poisoned_model/full_epoch_9.pth   --modelsave_path models/higher_budget/first_quarter  --save_epoch 19  --lr 0.01 --targets 1000 --recipe patch --start_from 10  --save_weights untimed --budget 0.1
python3 brew_poison.py --poisonkey 0 --modelkey 0 --deterministic --optimization basic --only_clean_training --epochs 10 --load_model models/higher_budget/first_quarter/clean_model/full_epoch_19.pth     --modelsave_path models/higher_budget/first_quarter  --save_epoch 29  --lr 0.01 --targets 1000 --recipe patch --start_from 20  --save_weights untimed --budget 0.1
python3 brew_poison.py --poisonkey 0 --modelkey 0 --deterministic --optimization basic --only_clean_training --epochs 10 --load_model models/higher_budget/first_quarter/clean_model/full_epoch_29.pth     --modelsave_path models/higher_budget/first_quarter  --save_epoch 39  --lr 0.01 --targets 1000 --recipe patch --start_from 30  --save_weights untimed --budget 0.1

# Second quarter poisoned
python3 brew_poison.py --poisonkey 0 --modelkey 0 --deterministic --optimization basic --only_clean_training --epochs 10                                                                                   --modelsave_path models/higher_budget/second_quarter --save_epoch 9   --lr 0.01 --targets 1000 --recipe patch                  --save_weights untimed --budget 0.1
python3 brew_poison.py --poisonkey 0 --modelkey 0 --deterministic --optimization basic --skip_clean_training --epochs 10 --load_model models/higher_budget/second_quarter/clean_model/full_epoch_9.pth     --modelsave_path models/higher_budget/second_quarter --save_epoch 19  --lr 0.01 --targets 1000 --recipe patch --start_from 10  --save_weights untimed --budget 0.1
python3 brew_poison.py --poisonkey 0 --modelkey 0 --deterministic --optimization basic --only_clean_training --epochs 10 --load_model models/higher_budget/second_quarter/poisoned_model/full_epoch_19.pth --modelsave_path models/higher_budget/second_quarter --save_epoch 29  --lr 0.01 --targets 1000 --recipe patch --start_from 20  --save_weights untimed --budget 0.1
python3 brew_poison.py --poisonkey 0 --modelkey 0 --deterministic --optimization basic --only_clean_training --epochs 10 --load_model models/higher_budget/second_quarter/clean_model/full_epoch_29.pth    --modelsave_path models/higher_budget/second_quarter --save_epoch 39  --lr 0.01 --targets 1000 --recipe patch --start_from 30  --save_weights untimed --budget 0.1

# Third quarter poisoned
python3 brew_poison.py --poisonkey 0 --modelkey 0 --deterministic --optimization basic --only_clean_training --epochs 10                                                                                   --modelsave_path models/higher_budget/third_quarter  --save_epoch 9   --lr 0.01 --targets 1000 --recipe patch                  --save_weights untimed --budget 0.1
python3 brew_poison.py --poisonkey 0 --modelkey 0 --deterministic --optimization basic --only_clean_training --epochs 10 --load_model models/higher_budget/third_quarter/clean_model/full_epoch_9.pth      --modelsave_path models/higher_budget/third_quarter  --save_epoch 19  --lr 0.01 --targets 1000 --recipe patch --start_from 10  --save_weights untimed --budget 0.1
python3 brew_poison.py --poisonkey 0 --modelkey 0 --deterministic --optimization basic --skip_clean_training --epochs 10 --load_model models/higher_budget/third_quarter/clean_model/full_epoch_19.pth     --modelsave_path models/higher_budget/third_quarter  --save_epoch 29  --lr 0.01 --targets 1000 --recipe patch --start_from 20  --save_weights untimed --budget 0.1
python3 brew_poison.py --poisonkey 0 --modelkey 0 --deterministic --optimization basic --only_clean_training --epochs 10 --load_model models/higher_budget/third_quarter/poisoned_model/full_epoch_29.pth  --modelsave_path models/higher_budget/third_quarter  --save_epoch 39  --lr 0.01 --targets 1000 --recipe patch --start_from 30  --save_weights untimed --budget 0.1

# Fourth quarter poisoned
python3 brew_poison.py --poisonkey 0 --modelkey 0 --deterministic --optimization basic --only_clean_training --epochs 10                                                                                   --modelsave_path models/higher_budget/fourth_quarter --save_epoch 9   --lr 0.01 --targets 1000 --recipe patch                  --save_weights untimed --budget 0.1
python3 brew_poison.py --poisonkey 0 --modelkey 0 --deterministic --optimization basic --only_clean_training --epochs 10 --load_model models/higher_budget/fourth_quarter/clean_model/full_epoch_9.pth     --modelsave_path models/higher_budget/fourth_quarter --save_epoch 19  --lr 0.01 --targets 1000 --recipe patch --start_from 10  --save_weights untimed --budget 0.1
python3 brew_poison.py --poisonkey 0 --modelkey 0 --deterministic --optimization basic --only_clean_training --epochs 10 --load_model models/higher_budget/fourth_quarter/clean_model/full_epoch_19.pth    --modelsave_path models/higher_budget/fourth_quarter --save_epoch 29  --lr 0.01 --targets 1000 --recipe patch --start_from 20  --save_weights untimed --budget 0.1
python3 brew_poison.py --poisonkey 0 --modelkey 0 --deterministic --optimization basic --skip_clean_training --epochs 10 --load_model models/higher_budget/fourth_quarter/clean_model/full_epoch_29.pth    --modelsave_path models/higher_budget/fourth_quarter --save_epoch 39  --lr 0.01 --targets 1000 --recipe patch --start_from 30  --save_weights untimed --budget 0.1

# All poisoned
python3 brew_poison.py --poisonkey 0 --modelkey 0 --deterministic --optimization basic --skip_clean_training --epochs 10                                                                                   --modelsave_path models/higher_budget/all_poisoned   --save_epoch 9   --lr 0.01 --targets 1000 --recipe patch                  --save_weights untimed --budget 0.1
python3 brew_poison.py --poisonkey 0 --modelkey 0 --deterministic --optimization basic --skip_clean_training --epochs 10 --load_model models/higher_budget/all_poisoned/poisoned_model/full_epoch_9.pth    --modelsave_path models/higher_budget/all_poisoned   --save_epoch 19  --lr 0.01 --targets 1000 --recipe patch --start_from 10  --save_weights untimed --budget 0.1
python3 brew_poison.py --poisonkey 0 --modelkey 0 --deterministic --optimization basic --skip_clean_training --epochs 10 --load_model models/higher_budget/all_poisoned/poisoned_model/full_epoch_19.pth   --modelsave_path models/higher_budget/all_poisoned   --save_epoch 29  --lr 0.01 --targets 1000 --recipe patch --start_from 20  --save_weights untimed --budget 0.1
python3 brew_poison.py --poisonkey 0 --modelkey 0 --deterministic --optimization basic --skip_clean_training --epochs 10 --load_model models/higher_budget/all_poisoned/poisoned_model/full_epoch_29.pth   --modelsave_path models/higher_budget/all_poisoned   --save_epoch 39  --lr 0.01 --targets 1000 --recipe patch --start_from 30  --save_weights untimed --budget 0.1

# A lot of clean epochs and then some poisoned
python3 brew_poison.py --poisonkey 0 --modelkey 0 --deterministic --optimization basic --only_clean_training --epochs 10                                                                                   --modelsave_path models/higher_budget/a_lot          --save_epoch 9   --lr 0.01 --targets 1000 --recipe patch                  --save_weights untimed --budget 0.1
python3 brew_poison.py --poisonkey 0 --modelkey 0 --deterministic --optimization basic --only_clean_training --epochs 10 --load_model models/higher_budget/a_lot/clean_model/full_epoch_9.pth              --modelsave_path models/higher_budget/a_lot          --save_epoch 19  --lr 0.01 --targets 1000 --recipe patch --start_from 10  --save_weights untimed --budget 0.1
python3 brew_poison.py --poisonkey 0 --modelkey 0 --deterministic --optimization basic --only_clean_training --epochs 10 --load_model models/higher_budget/a_lot/clean_model/full_epoch_19.pth             --modelsave_path models/higher_budget/a_lot          --save_epoch 29  --lr 0.01 --targets 1000 --recipe patch --start_from 20  --save_weights untimed --budget 0.1
python3 brew_poison.py --poisonkey 0 --modelkey 0 --deterministic --optimization basic --only_clean_training --epochs 10 --load_model models/higher_budget/a_lot/clean_model/full_epoch_29.pth             --modelsave_path models/higher_budget/a_lot          --save_epoch 39  --lr 0.01 --targets 1000 --recipe patch --start_from 30  --save_weights untimed --budget 0.1
python3 brew_poison.py --poisonkey 0 --modelkey 0 --deterministic --optimization basic --only_clean_training --epochs 10 --load_model models/higher_budget/a_lot/clean_model/full_epoch_39.pth             --modelsave_path models/higher_budget/a_lot          --save_epoch 49  --lr 0.01 --targets 1000 --recipe patch --start_from 40  --save_weights untimed --budget 0.1
python3 brew_poison.py --poisonkey 0 --modelkey 0 --deterministic --optimization basic --only_clean_training --epochs 10 --load_model models/higher_budget/a_lot/clean_model/full_epoch_49.pth             --modelsave_path models/higher_budget/a_lot          --save_epoch 59  --lr 0.01 --targets 1000 --recipe patch --start_from 50  --save_weights untimed --budget 0.1
python3 brew_poison.py --poisonkey 0 --modelkey 0 --deterministic --optimization basic --only_clean_training --epochs 10 --load_model models/higher_budget/a_lot/clean_model/full_epoch_59.pth             --modelsave_path models/higher_budget/a_lot          --save_epoch 69  --lr 0.01 --targets 1000 --recipe patch --start_from 60  --save_weights untimed --budget 0.1
python3 brew_poison.py --poisonkey 0 --modelkey 0 --deterministic --optimization basic --only_clean_training --epochs 10 --load_model models/higher_budget/a_lot/clean_model/full_epoch_69.pth             --modelsave_path models/higher_budget/a_lot          --save_epoch 79  --lr 0.01 --targets 1000 --recipe patch --start_from 70  --save_weights untimed --budget 0.1
python3 brew_poison.py --poisonkey 0 --modelkey 0 --deterministic --optimization basic --only_clean_training --epochs 10 --load_model models/higher_budget/a_lot/clean_model/full_epoch_79.pth             --modelsave_path models/higher_budget/a_lot          --save_epoch 89  --lr 0.01 --targets 1000 --recipe patch --start_from 80  --save_weights untimed --budget 0.1
python3 brew_poison.py --poisonkey 0 --modelkey 0 --deterministic --optimization basic --only_clean_training --epochs 10 --load_model models/higher_budget/a_lot/clean_model/full_epoch_89.pth             --modelsave_path models/higher_budget/a_lot          --save_epoch 99  --lr 0.01 --targets 1000 --recipe patch --start_from 90  --save_weights untimed --budget 0.1
python3 brew_poison.py --poisonkey 0 --modelkey 0 --deterministic --optimization basic --skip_clean_training --epochs 10 --load_model models/higher_budget/a_lot/clean_model/full_epoch_99.pth             --modelsave_path models/higher_budget/a_lot          --save_epoch 109 --lr 0.01 --targets 1000 --recipe patch --start_from 100 --save_weights untimed --budget 0.1