python3 brew_poison.py --poisonkey 0 --modelkey 0 --deterministic --save_weights timed --modelsave_path models/1 --epochs 2 --only_clean_training --net efficientnet-b8
python3 brew_poison.py --poisonkey 0 --modelkey 0 --deterministic --save_weights timed --modelsave_path models/2 --epochs 2 --only_clean_training --net efficientnet-b7
python3 brew_poison.py --poisonkey 0 --modelkey 0 --deterministic --save_weights timed --modelsave_path models/3 --epochs 2 --only_clean_training --net ResNet152
python3 brew_poison.py --poisonkey 0 --modelkey 0 --deterministic --save_weights timed --modelsave_path models/4 --epochs 2 --only_clean_training --net ResNet32-10
python3 brew_poison.py --poisonkey 0 --modelkey 0 --deterministic --save_weights timed --modelsave_path models/5 --epochs 2 --only_clean_training --net efficientnet-b6
python3 brew_poison.py --poisonkey 0 --modelkey 0 --deterministic --save_weights timed --modelsave_path models/6 --epochs 2 --only_clean_training --net ResNet101
python3 brew_poison.py --poisonkey 0 --modelkey 0 --deterministic --save_weights timed --modelsave_path models/7 --epochs 2 --only_clean_training --net ResNet28-10
python3 brew_poison.py --poisonkey 0 --modelkey 0 --deterministic --save_weights timed --modelsave_path models/8 --epochs 2 --only_clean_training --net efficientnet-b5
python3 brew_poison.py --poisonkey 0 --modelkey 0 --deterministic --save_weights timed --modelsave_path models/9 --epochs 2 --only_clean_training --net ResNet50
python3 brew_poison.py --poisonkey 0 --modelkey 0 --deterministic --save_weights timed --modelsave_path models/10 --epochs 2 --only_clean_training --net ResNet34
python3 brew_poison.py --poisonkey 0 --modelkey 0 --deterministic --save_weights timed --modelsave_path models/11 --epochs 2 --only_clean_training --net VGG19
python3 brew_poison.py --poisonkey 0 --modelkey 0 --deterministic --save_weights timed --modelsave_path models/12 --epochs 2 --only_clean_training --net efficientnet-b4
python3 brew_poison.py --poisonkey 0 --modelkey 0 --deterministic --save_weights timed --modelsave_path models/13 --epochs 2 --only_clean_training --net VGG16
python3 brew_poison.py --poisonkey 0 --modelkey 0 --deterministic --save_weights timed --modelsave_path models/14 --epochs 2 --only_clean_training --net efficientnet-b3
python3 brew_poison.py --poisonkey 0 --modelkey 0 --deterministic --save_weights timed --modelsave_path models/15 --epochs 2 --only_clean_training --net ResNet18
python3 brew_poison.py --poisonkey 0 --modelkey 0 --deterministic --save_weights timed --modelsave_path models/16 --epochs 2 --only_clean_training --net VGG13
python3 brew_poison.py --poisonkey 0 --modelkey 0 --deterministic --save_weights timed --modelsave_path models/17 --epochs 2 --only_clean_training --net VGG11
python3 brew_poison.py --poisonkey 0 --modelkey 0 --deterministic --save_weights timed --modelsave_path models/18 --epochs 2 --only_clean_training --net efficientnet-b2
python3 brew_poison.py --poisonkey 0 --modelkey 0 --deterministic --save_weights timed --modelsave_path models/19 --epochs 2 --only_clean_training --net efficientnet-b1
python3 brew_poison.py --poisonkey 0 --modelkey 0 --deterministic --save_weights timed --modelsave_path models/20 --epochs 2 --only_clean_training --net efficientnet-b0
python3 brew_poison.py --poisonkey 0 --modelkey 0 --deterministic --save_weights timed --modelsave_path models/21 --epochs 2 --only_clean_training --net ResNet20-4
python3 brew_poison.py --poisonkey 0 --modelkey 0 --deterministic --save_weights timed --modelsave_path models/22 --epochs 2 --only_clean_training --net ResNet20-3
python3 brew_poison.py --poisonkey 0 --modelkey 0 --deterministic --save_weights timed --modelsave_path models/23 --epochs 2 --only_clean_training --net MobileNetV2
python3 brew_poison.py --poisonkey 0 --modelkey 0 --deterministic --save_weights timed --modelsave_path models/24 --epochs 2 --only_clean_training --net ResNet110
python3 brew_poison.py --poisonkey 0 --modelkey 0 --deterministic --save_weights timed --modelsave_path models/25 --epochs 2 --only_clean_training --net ConvNet64
python3 brew_poison.py --poisonkey 0 --modelkey 0 --deterministic --save_weights timed --modelsave_path models/26 --epochs 2 --only_clean_training --net ConvNet128
python3 brew_poison.py --poisonkey 0 --modelkey 0 --deterministic --save_weights timed --modelsave_path models/27 --epochs 2 --only_clean_training --net ResNet20-2
python3 brew_poison.py --poisonkey 0 --modelkey 0 --deterministic --save_weights timed --modelsave_path models/28 --epochs 2 --only_clean_training --net ResNet56
python3 brew_poison.py --poisonkey 0 --modelkey 0 --deterministic --save_weights timed --modelsave_path models/29 --epochs 2 --only_clean_training --net ResNet44
python3 brew_poison.py --poisonkey 0 --modelkey 0 --deterministic --save_weights timed --modelsave_path models/30 --epochs 2 --only_clean_training --net ResNet32
python3 brew_poison.py --poisonkey 0 --modelkey 0 --deterministic --save_weights timed --modelsave_path models/31 --epochs 2 --only_clean_training --net ConvNetBN
python3 brew_poison.py --poisonkey 0 --modelkey 0 --deterministic --save_weights timed --modelsave_path models/32 --epochs 2 --only_clean_training --net ConvNet
python3 brew_poison.py --poisonkey 0 --modelkey 0 --deterministic --save_weights timed --modelsave_path models/33 --epochs 2 --only_clean_training --net ResNet20
python3 brew_poison.py --poisonkey 0 --modelkey 0 --deterministic --save_weights timed --modelsave_path models/34 --epochs 2 --only_clean_training --net alexnet-mp-bn
python3 brew_poison.py --poisonkey 0 --modelkey 0 --deterministic --save_weights timed --modelsave_path models/35 --epochs 2 --only_clean_training --net alexnet-mp
python3 brew_poison.py --poisonkey 0 --modelkey 0 --deterministic --save_weights timed --modelsave_path models/36 --epochs 2 --only_clean_training --net Linear
