python3 ../weight_analysis.py poisoned_model/epoch_0.pth poisoned_model/epoch_1.pth poisoned_model/epoch_2.pth
python3 ../weight_analysis.py poisoned_model/epoch_1.pth poisoned_model/epoch_2.pth poisoned_model/epoch_3.pth
python3 ../weight_analysis.py poisoned_model/epoch_2.pth poisoned_model/epoch_3.pth poisoned_model/epoch_4.pth
python3 ../weight_analysis.py poisoned_model/epoch_3.pth poisoned_model/epoch_4.pth poisoned_model/epoch_5.pth
python3 ../weight_analysis.py poisoned_model/epoch_4.pth poisoned_model/epoch_5.pth poisoned_model/epoch_6.pth
python3 ../weight_analysis.py poisoned_model/epoch_5.pth poisoned_model/epoch_6.pth poisoned_model/epoch_7.pth
python3 ../weight_analysis.py poisoned_model/epoch_6.pth poisoned_model/epoch_7.pth poisoned_model/epoch_8.pth
python3 ../weight_analysis.py poisoned_model/epoch_7.pth poisoned_model/epoch_8.pth poisoned_model/epoch_9.pth
python3 ../weight_analysis.py poisoned_model/epoch_8.pth poisoned_model/epoch_9.pth clean_model/epoch_10.pth
python3 ../weight_analysis.py poisoned_model/epoch_9.pth clean_model/epoch_10.pth clean_model/epoch_11.pth
python3 ../weight_analysis.py clean_model/epoch_10.pth clean_model/epoch_11.pth clean_model/epoch_12.pth
python3 ../weight_analysis.py clean_model/epoch_11.pth clean_model/epoch_12.pth clean_model/epoch_13.pth
python3 ../weight_analysis.py clean_model/epoch_12.pth clean_model/epoch_13.pth clean_model/epoch_14.pth
python3 ../weight_analysis.py clean_model/epoch_13.pth clean_model/epoch_14.pth clean_model/epoch_15.pth
python3 ../weight_analysis.py clean_model/epoch_14.pth clean_model/epoch_15.pth clean_model/epoch_16.pth
python3 ../weight_analysis.py clean_model/epoch_15.pth clean_model/epoch_16.pth clean_model/epoch_17.pth
python3 ../weight_analysis.py clean_model/epoch_16.pth clean_model/epoch_17.pth clean_model/epoch_18.pth
python3 ../weight_analysis.py clean_model/epoch_17.pth clean_model/epoch_18.pth clean_model/epoch_19.pth
python3 ../weight_analysis.py clean_model/epoch_18.pth clean_model/epoch_19.pth clean_model/epoch_20.pth
python3 ../weight_analysis.py clean_model/epoch_19.pth clean_model/epoch_20.pth clean_model/epoch_21.pth
python3 ../weight_analysis.py clean_model/epoch_20.pth clean_model/epoch_21.pth clean_model/epoch_22.pth
python3 ../weight_analysis.py clean_model/epoch_21.pth clean_model/epoch_22.pth clean_model/epoch_23.pth
python3 ../weight_analysis.py clean_model/epoch_22.pth clean_model/epoch_23.pth clean_model/epoch_24.pth
python3 ../weight_analysis.py clean_model/epoch_23.pth clean_model/epoch_24.pth clean_model/epoch_25.pth
python3 ../weight_analysis.py clean_model/epoch_24.pth clean_model/epoch_25.pth clean_model/epoch_26.pth
python3 ../weight_analysis.py clean_model/epoch_25.pth clean_model/epoch_26.pth clean_model/epoch_27.pth
python3 ../weight_analysis.py clean_model/epoch_26.pth clean_model/epoch_27.pth clean_model/epoch_28.pth
python3 ../weight_analysis.py clean_model/epoch_27.pth clean_model/epoch_28.pth clean_model/epoch_29.pth
python3 ../weight_analysis.py clean_model/epoch_28.pth clean_model/epoch_29.pth clean_model/epoch_30.pth
python3 ../weight_analysis.py clean_model/epoch_29.pth clean_model/epoch_30.pth clean_model/epoch_31.pth
python3 ../weight_analysis.py clean_model/epoch_30.pth clean_model/epoch_31.pth clean_model/epoch_32.pth
python3 ../weight_analysis.py clean_model/epoch_31.pth clean_model/epoch_32.pth clean_model/epoch_33.pth
python3 ../weight_analysis.py clean_model/epoch_32.pth clean_model/epoch_33.pth clean_model/epoch_34.pth
python3 ../weight_analysis.py clean_model/epoch_33.pth clean_model/epoch_34.pth clean_model/epoch_35.pth
python3 ../weight_analysis.py clean_model/epoch_34.pth clean_model/epoch_35.pth clean_model/epoch_36.pth
python3 ../weight_analysis.py clean_model/epoch_35.pth clean_model/epoch_36.pth clean_model/epoch_37.pth
python3 ../weight_analysis.py clean_model/epoch_36.pth clean_model/epoch_37.pth clean_model/epoch_38.pth
python3 ../weight_analysis.py clean_model/epoch_37.pth clean_model/epoch_38.pth clean_model/epoch_39.pth
python3 ../weight_analysis.py clean_model/epoch_38.pth clean_model/epoch_39.pth clean_model/epoch_40.pth
