python3 abs_change.py grad_desc_attack/seed_0/original_model/epoch_0.pth grad_desc_attack/seed_0/original_model/epoch_1.pth
python3 abs_change.py grad_desc_attack/seed_0/original_model/epoch_1.pth grad_desc_attack/seed_0/original_model/epoch_2.pth
python3 abs_change.py grad_desc_attack/seed_0/original_model/epoch_2.pth grad_desc_attack/seed_0/original_model/epoch_3.pth
python3 abs_change.py grad_desc_attack/seed_0/original_model/epoch_3.pth grad_desc_attack/seed_0/original_model/epoch_4.pth
python3 abs_change.py grad_desc_attack/seed_0/original_model/epoch_4.pth grad_desc_attack/seed_0/original_model/epoch_5.pth
python3 abs_change.py grad_desc_attack/seed_0/original_model/epoch_5.pth grad_desc_attack/seed_0/original_model/epoch_6.pth
python3 abs_change.py grad_desc_attack/seed_0/original_model/epoch_6.pth grad_desc_attack/seed_0/original_model/epoch_7.pth
python3 abs_change.py grad_desc_attack/seed_0/original_model/epoch_7.pth grad_desc_attack/seed_0/original_model/epoch_8.pth
python3 abs_change.py grad_desc_attack/seed_0/original_model/epoch_8.pth grad_desc_attack/seed_0/original_model/epoch_9.pth
python3 abs_change.py grad_desc_attack/seed_0/original_model/epoch_9.pth grad_desc_attack/seed_0/original_model/epoch_10.pth
python3 abs_change.py grad_desc_attack/seed_0/original_model/epoch_10.pth grad_desc_attack/seed_0/original_model/epoch_11.pth
python3 abs_change.py grad_desc_attack/seed_0/original_model/epoch_11.pth grad_desc_attack/seed_0/original_model/epoch_12.pth
python3 abs_change.py grad_desc_attack/seed_0/original_model/epoch_12.pth grad_desc_attack/seed_0/original_model/epoch_13.pth
python3 abs_change.py grad_desc_attack/seed_0/original_model/epoch_13.pth grad_desc_attack/seed_0/original_model/epoch_14.pth
python3 abs_change.py grad_desc_attack/seed_0/original_model/epoch_14.pth grad_desc_attack/seed_0/original_model/epoch_15.pth
python3 abs_change.py grad_desc_attack/seed_0/original_model/epoch_15.pth grad_desc_attack/seed_0/original_model/epoch_16.pth
python3 abs_change.py grad_desc_attack/seed_0/original_model/epoch_16.pth grad_desc_attack/seed_0/original_model/epoch_17.pth
python3 abs_change.py grad_desc_attack/seed_0/original_model/epoch_17.pth grad_desc_attack/seed_0/original_model/epoch_18.pth
python3 abs_change.py grad_desc_attack/seed_0/original_model/epoch_18.pth grad_desc_attack/seed_0/original_model/epoch_19.pth
python3 abs_change.py grad_desc_attack/seed_0/original_model/epoch_19.pth grad_desc_attack/seed_0/original_model/epoch_20.pth
python3 abs_change.py grad_desc_attack/seed_0/original_model/epoch_20.pth grad_desc_attack/seed_0/original_model/epoch_21.pth
python3 abs_change.py grad_desc_attack/seed_0/original_model/epoch_21.pth grad_desc_attack/seed_0/original_model/epoch_22.pth
python3 abs_change.py grad_desc_attack/seed_0/original_model/epoch_22.pth grad_desc_attack/seed_0/original_model/epoch_23.pth
python3 abs_change.py grad_desc_attack/seed_0/original_model/epoch_23.pth grad_desc_attack/seed_0/original_model/epoch_24.pth
python3 abs_change.py grad_desc_attack/seed_0/original_model/epoch_24.pth grad_desc_attack/seed_0/original_model/epoch_25.pth
python3 abs_change.py grad_desc_attack/seed_0/original_model/epoch_25.pth grad_desc_attack/seed_0/original_model/epoch_26.pth
python3 abs_change.py grad_desc_attack/seed_0/original_model/epoch_26.pth grad_desc_attack/seed_0/original_model/epoch_27.pth
python3 abs_change.py grad_desc_attack/seed_0/original_model/epoch_27.pth grad_desc_attack/seed_0/original_model/epoch_28.pth
python3 abs_change.py grad_desc_attack/seed_0/original_model/epoch_28.pth grad_desc_attack/seed_0/original_model/epoch_29.pth
python3 abs_change.py grad_desc_attack/seed_0/original_model/epoch_29.pth grad_desc_attack/seed_0/original_model/epoch_30.pth
python3 abs_change.py grad_desc_attack/seed_0/original_model/epoch_30.pth grad_desc_attack/seed_0/original_model/epoch_31.pth
python3 abs_change.py grad_desc_attack/seed_0/original_model/epoch_31.pth grad_desc_attack/seed_0/original_model/epoch_32.pth
python3 abs_change.py grad_desc_attack/seed_0/original_model/epoch_32.pth grad_desc_attack/seed_0/original_model/epoch_33.pth
python3 abs_change.py grad_desc_attack/seed_0/original_model/epoch_33.pth grad_desc_attack/seed_0/original_model/epoch_34.pth
python3 abs_change.py grad_desc_attack/seed_0/original_model/epoch_34.pth grad_desc_attack/seed_0/original_model/epoch_35.pth
python3 abs_change.py grad_desc_attack/seed_0/original_model/epoch_35.pth grad_desc_attack/seed_0/original_model/epoch_36.pth
python3 abs_change.py grad_desc_attack/seed_0/original_model/epoch_36.pth grad_desc_attack/seed_0/original_model/epoch_37.pth
python3 abs_change.py grad_desc_attack/seed_0/original_model/epoch_37.pth grad_desc_attack/seed_0/original_model/epoch_38.pth
python3 abs_change.py grad_desc_attack/seed_0/original_model/epoch_38.pth grad_desc_attack/seed_0/original_model/epoch_39.pth
python3 abs_change.py grad_desc_attack/seed_0/original_model/epoch_39.pth grad_desc_attack/seed_0/original_model/epoch_40.pth
python3 abs_change.py grad_desc_attack/seed_0/original_model/epoch_40.pth grad_desc_attack/seed_0/original_model/epoch_41.pth
python3 abs_change.py grad_desc_attack/seed_0/original_model/epoch_41.pth grad_desc_attack/seed_0/original_model/epoch_42.pth
python3 abs_change.py grad_desc_attack/seed_0/original_model/epoch_42.pth grad_desc_attack/seed_0/original_model/epoch_43.pth
python3 abs_change.py grad_desc_attack/seed_0/original_model/epoch_43.pth grad_desc_attack/seed_0/original_model/epoch_44.pth
python3 abs_change.py grad_desc_attack/seed_0/original_model/epoch_44.pth grad_desc_attack/seed_0/original_model/epoch_45.pth
python3 abs_change.py grad_desc_attack/seed_0/original_model/epoch_45.pth grad_desc_attack/seed_0/original_model/epoch_46.pth
python3 abs_change.py grad_desc_attack/seed_0/original_model/epoch_46.pth grad_desc_attack/seed_0/original_model/epoch_47.pth
python3 abs_change.py grad_desc_attack/seed_0/original_model/epoch_47.pth grad_desc_attack/seed_0/original_model/epoch_48.pth
python3 abs_change.py grad_desc_attack/seed_0/original_model/epoch_48.pth grad_desc_attack/seed_0/original_model/epoch_49.pth
python3 abs_change.py grad_desc_attack/seed_0/original_model/epoch_49.pth grad_desc_attack/seed_0/original_model/epoch_50.pth
python3 abs_change.py grad_desc_attack/seed_0/original_model/epoch_50.pth grad_desc_attack/seed_0/original_model/epoch_51.pth
python3 abs_change.py grad_desc_attack/seed_0/original_model/epoch_51.pth grad_desc_attack/seed_0/original_model/epoch_52.pth
python3 abs_change.py grad_desc_attack/seed_0/original_model/epoch_52.pth grad_desc_attack/seed_0/original_model/epoch_53.pth
python3 abs_change.py grad_desc_attack/seed_0/original_model/epoch_53.pth grad_desc_attack/seed_0/original_model/epoch_54.pth
python3 abs_change.py grad_desc_attack/seed_0/original_model/epoch_54.pth grad_desc_attack/seed_0/original_model/epoch_55.pth
python3 abs_change.py grad_desc_attack/seed_0/original_model/epoch_55.pth grad_desc_attack/seed_0/original_model/epoch_56.pth
python3 abs_change.py grad_desc_attack/seed_0/original_model/epoch_56.pth grad_desc_attack/seed_0/original_model/epoch_57.pth
python3 abs_change.py grad_desc_attack/seed_0/original_model/epoch_57.pth grad_desc_attack/seed_0/original_model/epoch_58.pth
python3 abs_change.py grad_desc_attack/seed_0/original_model/epoch_58.pth grad_desc_attack/seed_0/original_model/epoch_59.pth
python3 abs_change.py grad_desc_attack/seed_0/original_model/epoch_59.pth grad_desc_attack/seed_0/original_model/epoch_60.pth
python3 abs_change.py grad_desc_attack/seed_0/original_model/epoch_60.pth grad_desc_attack/seed_0/original_model/epoch_61.pth
python3 abs_change.py grad_desc_attack/seed_0/original_model/epoch_61.pth grad_desc_attack/seed_0/original_model/epoch_62.pth
python3 abs_change.py grad_desc_attack/seed_0/original_model/epoch_62.pth grad_desc_attack/seed_0/original_model/epoch_63.pth
python3 abs_change.py grad_desc_attack/seed_0/original_model/epoch_63.pth grad_desc_attack/seed_0/original_model/epoch_64.pth
python3 abs_change.py grad_desc_attack/seed_0/original_model/epoch_64.pth grad_desc_attack/seed_0/original_model/epoch_65.pth
python3 abs_change.py grad_desc_attack/seed_0/original_model/epoch_65.pth grad_desc_attack/seed_0/original_model/epoch_66.pth
python3 abs_change.py grad_desc_attack/seed_0/original_model/epoch_66.pth grad_desc_attack/seed_0/original_model/epoch_67.pth
python3 abs_change.py grad_desc_attack/seed_0/original_model/epoch_67.pth grad_desc_attack/seed_0/original_model/epoch_68.pth
python3 abs_change.py grad_desc_attack/seed_0/original_model/epoch_68.pth grad_desc_attack/seed_0/original_model/epoch_69.pth
python3 abs_change.py grad_desc_attack/seed_0/original_model/epoch_69.pth grad_desc_attack/seed_0/original_model/epoch_70.pth
python3 abs_change.py grad_desc_attack/seed_0/original_model/epoch_70.pth grad_desc_attack/seed_0/original_model/epoch_71.pth
python3 abs_change.py grad_desc_attack/seed_0/original_model/epoch_71.pth grad_desc_attack/seed_0/original_model/epoch_72.pth
python3 abs_change.py grad_desc_attack/seed_0/original_model/epoch_72.pth grad_desc_attack/seed_0/original_model/epoch_73.pth
python3 abs_change.py grad_desc_attack/seed_0/original_model/epoch_73.pth grad_desc_attack/seed_0/original_model/epoch_74.pth
python3 abs_change.py grad_desc_attack/seed_0/original_model/epoch_74.pth grad_desc_attack/seed_0/original_model/epoch_75.pth
python3 abs_change.py grad_desc_attack/seed_0/original_model/epoch_75.pth grad_desc_attack/seed_0/original_model/epoch_76.pth
python3 abs_change.py grad_desc_attack/seed_0/original_model/epoch_76.pth grad_desc_attack/seed_0/original_model/epoch_77.pth
python3 abs_change.py grad_desc_attack/seed_0/original_model/epoch_77.pth grad_desc_attack/seed_0/original_model/epoch_78.pth
python3 abs_change.py grad_desc_attack/seed_0/original_model/epoch_78.pth grad_desc_attack/seed_0/original_model/epoch_79.pth
