python3 abs_change_2.py original_model/epoch_0.pth original_model/epoch_1.pth
python3 abs_change_2.py original_model/epoch_1.pth original_model/epoch_2.pth
python3 abs_change_2.py original_model/epoch_2.pth original_model/epoch_3.pth
python3 abs_change_2.py original_model/epoch_3.pth original_model/epoch_4.pth
python3 abs_change_2.py original_model/epoch_4.pth original_model/epoch_5.pth
python3 abs_change_2.py original_model/epoch_5.pth original_model/epoch_6.pth
python3 abs_change_2.py original_model/epoch_6.pth original_model/epoch_7.pth
python3 abs_change_2.py original_model/epoch_7.pth original_model/epoch_8.pth
python3 abs_change_2.py original_model/epoch_8.pth original_model/epoch_9.pth

python3 abs_change_2.py poisoned_model/epoch_0.pth poisoned_model/epoch_1.pth
python3 abs_change_2.py poisoned_model/epoch_1.pth poisoned_model/epoch_2.pth
python3 abs_change_2.py poisoned_model/epoch_2.pth poisoned_model/epoch_3.pth
python3 abs_change_2.py poisoned_model/epoch_3.pth poisoned_model/epoch_4.pth
python3 abs_change_2.py poisoned_model/epoch_4.pth poisoned_model/epoch_5.pth
python3 abs_change_2.py poisoned_model/epoch_5.pth poisoned_model/epoch_6.pth
python3 abs_change_2.py poisoned_model/epoch_6.pth poisoned_model/epoch_7.pth
python3 abs_change_2.py poisoned_model/epoch_7.pth poisoned_model/epoch_8.pth
python3 abs_change_2.py poisoned_model/epoch_8.pth poisoned_model/epoch_9.pth
