python3 abs_change.py patch_attack/seed_1/original_model/epoch_0.pth patch_attack/seed_1/original_model/epoch_1.pth
python3 abs_change.py patch_attack/seed_1/original_model/epoch_1.pth patch_attack/seed_1/original_model/epoch_2.pth
python3 abs_change.py patch_attack/seed_1/original_model/epoch_2.pth patch_attack/seed_1/original_model/epoch_3.pth
python3 abs_change.py patch_attack/seed_1/original_model/epoch_3.pth patch_attack/seed_1/original_model/epoch_4.pth
python3 abs_change.py patch_attack/seed_1/original_model/epoch_4.pth patch_attack/seed_1/original_model/epoch_5.pth
python3 abs_change.py patch_attack/seed_1/original_model/epoch_5.pth patch_attack/seed_1/original_model/epoch_6.pth
python3 abs_change.py patch_attack/seed_1/original_model/epoch_6.pth patch_attack/seed_1/original_model/epoch_7.pth
python3 abs_change.py patch_attack/seed_1/original_model/epoch_7.pth patch_attack/seed_1/original_model/epoch_8.pth
python3 abs_change.py patch_attack/seed_1/original_model/epoch_8.pth patch_attack/seed_1/original_model/epoch_9.pth
python3 abs_change.py patch_attack/seed_1/original_model/epoch_9.pth patch_attack/seed_1/original_model/epoch_10.pth
python3 abs_change.py patch_attack/seed_1/original_model/epoch_10.pth patch_attack/seed_1/original_model/epoch_11.pth
python3 abs_change.py patch_attack/seed_1/original_model/epoch_11.pth patch_attack/seed_1/original_model/epoch_12.pth
python3 abs_change.py patch_attack/seed_1/original_model/epoch_12.pth patch_attack/seed_1/original_model/epoch_13.pth
python3 abs_change.py patch_attack/seed_1/original_model/epoch_13.pth patch_attack/seed_1/original_model/epoch_14.pth
python3 abs_change.py patch_attack/seed_1/original_model/epoch_14.pth patch_attack/seed_1/original_model/epoch_15.pth
python3 abs_change.py patch_attack/seed_1/original_model/epoch_15.pth patch_attack/seed_1/original_model/epoch_16.pth
python3 abs_change.py patch_attack/seed_1/original_model/epoch_16.pth patch_attack/seed_1/original_model/epoch_17.pth
python3 abs_change.py patch_attack/seed_1/original_model/epoch_17.pth patch_attack/seed_1/original_model/epoch_18.pth
python3 abs_change.py patch_attack/seed_1/original_model/epoch_18.pth patch_attack/seed_1/original_model/epoch_19.pth
python3 abs_change.py patch_attack/seed_1/original_model/epoch_19.pth patch_attack/seed_1/original_model/epoch_20.pth
python3 abs_change.py patch_attack/seed_1/original_model/epoch_20.pth patch_attack/seed_1/original_model/epoch_21.pth
python3 abs_change.py patch_attack/seed_1/original_model/epoch_21.pth patch_attack/seed_1/original_model/epoch_22.pth
python3 abs_change.py patch_attack/seed_1/original_model/epoch_22.pth patch_attack/seed_1/original_model/epoch_23.pth
python3 abs_change.py patch_attack/seed_1/original_model/epoch_23.pth patch_attack/seed_1/original_model/epoch_24.pth
python3 abs_change.py patch_attack/seed_1/original_model/epoch_24.pth patch_attack/seed_1/original_model/epoch_25.pth
python3 abs_change.py patch_attack/seed_1/original_model/epoch_25.pth patch_attack/seed_1/original_model/epoch_26.pth
python3 abs_change.py patch_attack/seed_1/original_model/epoch_26.pth patch_attack/seed_1/original_model/epoch_27.pth
python3 abs_change.py patch_attack/seed_1/original_model/epoch_27.pth patch_attack/seed_1/original_model/epoch_28.pth
python3 abs_change.py patch_attack/seed_1/original_model/epoch_28.pth patch_attack/seed_1/original_model/epoch_29.pth
python3 abs_change.py patch_attack/seed_1/original_model/epoch_29.pth patch_attack/seed_1/original_model/epoch_30.pth
python3 abs_change.py patch_attack/seed_1/original_model/epoch_30.pth patch_attack/seed_1/original_model/epoch_31.pth
python3 abs_change.py patch_attack/seed_1/original_model/epoch_31.pth patch_attack/seed_1/original_model/epoch_32.pth
python3 abs_change.py patch_attack/seed_1/original_model/epoch_32.pth patch_attack/seed_1/original_model/epoch_33.pth
python3 abs_change.py patch_attack/seed_1/original_model/epoch_33.pth patch_attack/seed_1/original_model/epoch_34.pth
python3 abs_change.py patch_attack/seed_1/original_model/epoch_34.pth patch_attack/seed_1/original_model/epoch_35.pth
python3 abs_change.py patch_attack/seed_1/original_model/epoch_35.pth patch_attack/seed_1/original_model/epoch_36.pth
python3 abs_change.py patch_attack/seed_1/original_model/epoch_36.pth patch_attack/seed_1/original_model/epoch_37.pth
python3 abs_change.py patch_attack/seed_1/original_model/epoch_37.pth patch_attack/seed_1/original_model/epoch_38.pth
python3 abs_change.py patch_attack/seed_1/original_model/epoch_38.pth patch_attack/seed_1/original_model/epoch_39.pth


python3 abs_change.py patch_attack/seed_1/poisoned_model/epoch_0.pth patch_attack/seed_1/poisoned_model/epoch_1.pth
python3 abs_change.py patch_attack/seed_1/poisoned_model/epoch_1.pth patch_attack/seed_1/poisoned_model/epoch_2.pth
python3 abs_change.py patch_attack/seed_1/poisoned_model/epoch_2.pth patch_attack/seed_1/poisoned_model/epoch_3.pth
python3 abs_change.py patch_attack/seed_1/poisoned_model/epoch_3.pth patch_attack/seed_1/poisoned_model/epoch_4.pth
python3 abs_change.py patch_attack/seed_1/poisoned_model/epoch_4.pth patch_attack/seed_1/poisoned_model/epoch_5.pth
python3 abs_change.py patch_attack/seed_1/poisoned_model/epoch_5.pth patch_attack/seed_1/poisoned_model/epoch_6.pth
python3 abs_change.py patch_attack/seed_1/poisoned_model/epoch_6.pth patch_attack/seed_1/poisoned_model/epoch_7.pth
python3 abs_change.py patch_attack/seed_1/poisoned_model/epoch_7.pth patch_attack/seed_1/poisoned_model/epoch_8.pth
python3 abs_change.py patch_attack/seed_1/poisoned_model/epoch_8.pth patch_attack/seed_1/poisoned_model/epoch_9.pth
python3 abs_change.py patch_attack/seed_1/poisoned_model/epoch_9.pth patch_attack/seed_1/poisoned_model/epoch_10.pth
python3 abs_change.py patch_attack/seed_1/poisoned_model/epoch_10.pth patch_attack/seed_1/poisoned_model/epoch_11.pth
python3 abs_change.py patch_attack/seed_1/poisoned_model/epoch_11.pth patch_attack/seed_1/poisoned_model/epoch_12.pth
python3 abs_change.py patch_attack/seed_1/poisoned_model/epoch_12.pth patch_attack/seed_1/poisoned_model/epoch_13.pth
python3 abs_change.py patch_attack/seed_1/poisoned_model/epoch_13.pth patch_attack/seed_1/poisoned_model/epoch_14.pth
python3 abs_change.py patch_attack/seed_1/poisoned_model/epoch_14.pth patch_attack/seed_1/poisoned_model/epoch_15.pth
python3 abs_change.py patch_attack/seed_1/poisoned_model/epoch_15.pth patch_attack/seed_1/poisoned_model/epoch_16.pth
python3 abs_change.py patch_attack/seed_1/poisoned_model/epoch_16.pth patch_attack/seed_1/poisoned_model/epoch_17.pth
python3 abs_change.py patch_attack/seed_1/poisoned_model/epoch_17.pth patch_attack/seed_1/poisoned_model/epoch_18.pth
python3 abs_change.py patch_attack/seed_1/poisoned_model/epoch_18.pth patch_attack/seed_1/poisoned_model/epoch_19.pth
python3 abs_change.py patch_attack/seed_1/poisoned_model/epoch_19.pth patch_attack/seed_1/poisoned_model/epoch_20.pth
python3 abs_change.py patch_attack/seed_1/poisoned_model/epoch_20.pth patch_attack/seed_1/poisoned_model/epoch_21.pth
python3 abs_change.py patch_attack/seed_1/poisoned_model/epoch_21.pth patch_attack/seed_1/poisoned_model/epoch_22.pth
python3 abs_change.py patch_attack/seed_1/poisoned_model/epoch_22.pth patch_attack/seed_1/poisoned_model/epoch_23.pth
python3 abs_change.py patch_attack/seed_1/poisoned_model/epoch_23.pth patch_attack/seed_1/poisoned_model/epoch_24.pth
python3 abs_change.py patch_attack/seed_1/poisoned_model/epoch_24.pth patch_attack/seed_1/poisoned_model/epoch_25.pth
python3 abs_change.py patch_attack/seed_1/poisoned_model/epoch_25.pth patch_attack/seed_1/poisoned_model/epoch_26.pth
python3 abs_change.py patch_attack/seed_1/poisoned_model/epoch_26.pth patch_attack/seed_1/poisoned_model/epoch_27.pth
python3 abs_change.py patch_attack/seed_1/poisoned_model/epoch_27.pth patch_attack/seed_1/poisoned_model/epoch_28.pth
python3 abs_change.py patch_attack/seed_1/poisoned_model/epoch_28.pth patch_attack/seed_1/poisoned_model/epoch_29.pth
python3 abs_change.py patch_attack/seed_1/poisoned_model/epoch_29.pth patch_attack/seed_1/poisoned_model/epoch_30.pth
python3 abs_change.py patch_attack/seed_1/poisoned_model/epoch_30.pth patch_attack/seed_1/poisoned_model/epoch_31.pth
python3 abs_change.py patch_attack/seed_1/poisoned_model/epoch_31.pth patch_attack/seed_1/poisoned_model/epoch_32.pth
python3 abs_change.py patch_attack/seed_1/poisoned_model/epoch_32.pth patch_attack/seed_1/poisoned_model/epoch_33.pth
python3 abs_change.py patch_attack/seed_1/poisoned_model/epoch_33.pth patch_attack/seed_1/poisoned_model/epoch_34.pth
python3 abs_change.py patch_attack/seed_1/poisoned_model/epoch_34.pth patch_attack/seed_1/poisoned_model/epoch_35.pth
python3 abs_change.py patch_attack/seed_1/poisoned_model/epoch_35.pth patch_attack/seed_1/poisoned_model/epoch_36.pth
python3 abs_change.py patch_attack/seed_1/poisoned_model/epoch_36.pth patch_attack/seed_1/poisoned_model/epoch_37.pth
python3 abs_change.py patch_attack/seed_1/poisoned_model/epoch_37.pth patch_attack/seed_1/poisoned_model/epoch_38.pth
python3 abs_change.py patch_attack/seed_1/poisoned_model/epoch_38.pth patch_attack/seed_1/poisoned_model/epoch_39.pth
