python3 weight_analysis.py 1/clean_model/epoch_0.pth 1/clean_model/epoch_1.pth
python3 weight_analysis.py 2/clean_model/epoch_0.pth 2/clean_model/epoch_1.pth
python3 weight_analysis.py 3/clean_model/epoch_0.pth 3/clean_model/epoch_1.pth
python3 weight_analysis.py 4/clean_model/epoch_0.pth 4/clean_model/epoch_1.pth
python3 weight_analysis.py 5/clean_model/epoch_0.pth 5/clean_model/epoch_1.pth
python3 weight_analysis.py 6/clean_model/epoch_0.pth 6/clean_model/epoch_1.pth
python3 weight_analysis.py 7/clean_model/epoch_0.pth 7/clean_model/epoch_1.pth
python3 weight_analysis.py 8/clean_model/epoch_0.pth 8/clean_model/epoch_1.pth
python3 weight_analysis.py 9/clean_model/epoch_0.pth 9/clean_model/epoch_1.pth
python3 weight_analysis.py 10/clean_model/epoch_0.pth 10/clean_model/epoch_1.pth
python3 weight_analysis.py 11/clean_model/epoch_0.pth 11/clean_model/epoch_1.pth
python3 weight_analysis.py 12/clean_model/epoch_0.pth 12/clean_model/epoch_1.pth
python3 weight_analysis.py 13/clean_model/epoch_0.pth 13/clean_model/epoch_1.pth
python3 weight_analysis.py 14/clean_model/epoch_0.pth 14/clean_model/epoch_1.pth
python3 weight_analysis.py 15/clean_model/epoch_0.pth 15/clean_model/epoch_1.pth
python3 weight_analysis.py 16/clean_model/epoch_0.pth 16/clean_model/epoch_1.pth
python3 weight_analysis.py 17/clean_model/epoch_0.pth 17/clean_model/epoch_1.pth
python3 weight_analysis.py 18/clean_model/epoch_0.pth 18/clean_model/epoch_1.pth
python3 weight_analysis.py 19/clean_model/epoch_0.pth 19/clean_model/epoch_1.pth
python3 weight_analysis.py 20/clean_model/epoch_0.pth 20/clean_model/epoch_1.pth
python3 weight_analysis.py 21/clean_model/epoch_0.pth 21/clean_model/epoch_1.pth
python3 weight_analysis.py 22/clean_model/epoch_0.pth 22/clean_model/epoch_1.pth
python3 weight_analysis.py 23/clean_model/epoch_0.pth 23/clean_model/epoch_1.pth
python3 weight_analysis.py 24/clean_model/epoch_0.pth 24/clean_model/epoch_1.pth
python3 weight_analysis.py 25/clean_model/epoch_0.pth 25/clean_model/epoch_1.pth
python3 weight_analysis.py 26/clean_model/epoch_0.pth 26/clean_model/epoch_1.pth
python3 weight_analysis.py 27/clean_model/epoch_0.pth 27/clean_model/epoch_1.pth
python3 weight_analysis.py 28/clean_model/epoch_0.pth 28/clean_model/epoch_1.pth
python3 weight_analysis.py 29/clean_model/epoch_0.pth 29/clean_model/epoch_1.pth
python3 weight_analysis.py 30/clean_model/epoch_0.pth 30/clean_model/epoch_1.pth
python3 weight_analysis.py 31/clean_model/epoch_0.pth 31/clean_model/epoch_1.pth
python3 weight_analysis.py 32/clean_model/epoch_0.pth 32/clean_model/epoch_1.pth
python3 weight_analysis.py 33/clean_model/epoch_0.pth 33/clean_model/epoch_1.pth
python3 weight_analysis.py 34/clean_model/epoch_0.pth 34/clean_model/epoch_1.pth
python3 weight_analysis.py 35/clean_model/epoch_0.pth 35/clean_model/epoch_1.pth
python3 weight_analysis.py 36/clean_model/epoch_0.pth 36/clean_model/epoch_1.pth
